version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
  test:
    image: mhart/alpine-node:7.9.0
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      NODE_ENV: testing
    command:
      /bin/sh -c "./node_modules/.bin/ava test/unit/*.js"
  db:
    image: couchdb:1.6.1
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    ports:
      - "5984:5984"

  redis:
    image: redis:3.0.7-alpine
    ports:
      - "6379:6379"
